### ISSUE TITLE
pretrained model location

### ISSUE THREAD

**Issue by vasanthsarathy** [Sandesh816/Argument-Quality-Analysis-Application#2]
Need to provide a link to the folder where the pretrained model is stored.

**Comment by Sandesh816** [comment]
Here is the link to the Google Drive folder with the model:
https://drive.google.com/drive/folders/1F3skwVf3pujt3D6gbzcJGbxahrgzjxsA?usp=drive_link

Also, I have uploaded the Jupyter Notebook with the script (commented) to train the model
